### Add new user
POST http://localhost:8080/user
Content-Type: application/json

{
    "name": "new user",
    "username": "new user am i",
    "email": "new@user.com"
}

### get all users
GET http://localhost:8080/users